sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
    - NODE_VERSION=stable
    - SAUCE_USERNAME="kaazing-build"
    - SAUCE_ACCESS_KEY="f350bbbb-376e-4c0e-b7b6-ae78f58f67f2"
  matrix:
    - platform=Linux browser=firefox version=43
    - platform=Linux browser=firefox version=dev
    - platform=Linux browser=chrome version=47
    - platform=Linux browser=chrome version=dev
    - platform="Windows 10" browser=microsoftedge version=20
    - platform="Windows 10" browser="internet explorer" version=11
    - platform="Windows 8" browser="internet explorer" version=10
    - platform="Windows 7" browser="internet explorer" version=9
    - platform="Windows 7" browser="internet explorer" version=8
    - platform="OS X 10.11" browser=safari version=9
    # not working with current version on webdriverio
    # please see https://github.com/webdriverio/webdriverio/issues/865
    # - platform=Linux browser=android version=5.1 device="Android Emulator"
    - platform="OS X 10.10" browser=iphone version=9.2 device="iPad Retina"
before_install:
  - ./sauce_connect_setup.sh
install:
  - nvm install $NODE_VERSION
  - npm install -g grunt-cli
  - npm install
script:
  - grunt sauceTest
