sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
    - NODE_VERSION=stable
    - SAUCE_USERNAME="kaazing-k3po"
    - SAUCE_ACCESS_KEY="14505593-10b3-4fa5-a592-ff3e88eed11d"
  matrix:
    - platform="Linux" browser="firefox" version="44.0"
    # not starting on Sauce Labs(build errors)
    # - platform="Linux" browser="firefox" version="dev"
    - platform="Linux" browser="chrome" version="48.0"
    - platform="Windows 10" browser="chrome" version="dev"
    - platform="Windows 10" browser="MicrosoftEdge" version="20.10240"
    - platform="Windows 10" browser="internet explorer" version="11.0"
    - platform="Windows 8" browser="internet explorer" version="10.0"
    - platform="Windows 7" browser="internet explorer" version="9.0"
    - platform="Windows 7" browser="internet explorer" version="8.0"
    - platform="OS X 10.11" browser="safari" version="9.0"
    # not working with current version on webdriverio
    # please see https://github.com/webdriverio/webdriverio/issues/865
    # - platform="Linux" browser="android" version="4.2" device="Android Emulator"
    - platform="OS X 10.10" browser="iphone" version="8.1" device="iPad 2"
    - platform="OS X 10.9" browser="iphone" version="7.1" device="iPad Retina (64-bit)"
before_install:
  - ./sauce_connect_setup.sh
install:
  - nvm install $NODE_VERSION
  - npm install -g grunt-cli
  - npm install
script:
  - grunt sauceTest
